### ISSUE TITLE
FATAL: This installer only works on Apple M1 Macs

### ISSUE THREAD

**Issue by willyk0** [carlosonunez/obs-installer-for-apple-silicon#1]
I get error FATAL: This installer only works on Apple M1 Macs on a M1 Macbook Air

this_is_not_an_m1_mac() {
  test "$(uname)" != "Darwin" || test "$(uname -p)" != "arm64"
}

I assume the error is that uname -p returns "arm", not "arm64"

% uname -p
arm

**Comment by carlosonunez** [comment]
Thanks for the issue! Which M1 Mac are you installing it on? On MacBooks, `uname -p` returns `arm64`.

**Comment by willyk0** [comment]
Pasting directly from "About this Mac", sorry for the spanish localization (I expect it's enough understandable)

  Nombre del modelo:	MacBook Air
  Identificador del modelo:	MacBookAir10,1
  Chip:	Apple M1
  Cantidad total de núcleos:	8 (4 de rendimiento y 4 de eficiencia)
  Memoria:	8 GB
  Versión del firmware del sistema:	6723.120.36
  Versión del cargador del sistema operativo:	6723.120.36

**Comment by willyk0** [comment]
BTW, changing "arm64" to "arm" works for me flawlessly.

**Comment by carlosonunez** [comment]
That's crazy interesting. I'll fix.

**Comment by carlosonunez** [comment]
Fixed. Closing. Let me know if you encounter any other issues!

**Comment by ethali** [comment]
I think 

```swift
this_is_not_an_m1_mac() {
  test "$(uname)" != "Darwin" ||
    (test "$(uname -p)" != "arm64" &&
    test "$(uname -p)" != "arm")
}
```
would be better.

My MacBook Pro M1 shows "arm" so the test fails.

**Comment by carlosonunez** [comment]
Thanks for the submission! Mind putting in a quick PR for that?

**Comment by jensenharris** [comment]
> I think
> 
> ```swift
> this_is_not_an_m1_mac() {
>   test "$(uname)" != "Darwin" ||
>     (test "$(uname -p)" != "arm64" &&
>     test "$(uname -p)" != "arm")
> }
> ```
> 
> would be better.
> 
> My MacBook Pro M1 shows "arm" so the test fails.

Yes, this is the right fix. Currently, the build process short circuits if `uname -p` is `arm`

**Comment by RayPS** [comment]
I still having the same issue.
<img width="680" alt="Screenshot 2021-09-07 at 02 09 25@2x" src="https://user-images.githubusercontent.com/1941540/132251447-1a854092-eb1f-44c1-8d1e-af46266dc7ed.png">

**Comment by RayPS** [comment]
After bypassing `this_is_not_an_m1_mac()`, I got this error

```shell
OBS_VERSION=27.1.0-rc2 ./install.sh

[Tue Sep  7 02:01:08 CST 2021] INFO: Installing build dependencies
Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake
==> Downloading https://download.videolan.org/vlc/3.0.16/macosx/vlc-3.0.16-intel64.dmg
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/b28e39f23e2e1663a9a9209a61bd63716e57c8636a6713aa43b7fc3e40320ffd--vlc-3.0.16-intel64.dmg
==> Installing Cask vlc
==> Moving App 'VLC.app' to '/Applications/VLC.app'
==> Linking Binary 'vlc.wrapper.sh' to '/opt/homebrew/bin/vlc'
🍺  vlc was successfully installed!
Warning: akeru-inc/tap/xcnotary 0.4.8 is already installed and up-to-date.
To reinstall 0.4.8, run:
  brew reinstall xcnotary
Warning: cmake 3.21.2 is already installed and up-to-date.
To reinstall 3.21.2, run:
  brew reinstall cmake
Warning: cmocka 1.1.5 is already installed and up-to-date.
To reinstall 1.1.5, run:
  brew reinstall cmocka
Warning: ffmpeg 4.4_2 is already installed and up-to-date.
To reinstall 4.4_2, run:
  brew reinstall ffmpeg
Warning: qt@5 5.15.2 is already installed and up-to-date.
To reinstall 5.15.2, run:
  brew reinstall qt@5
Warning: swig 4.0.2 is already installed and up-to-date.
To reinstall 4.0.2, run:
  brew reinstall swig
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
[Tue Sep  7 02:01:37 CST 2021] FATAL: Unable to install one or more OBS dependencies. See log above for more details.
```

**Comment by carlosonunez** [comment]
Is the shell that you ran this from running in Rosetta mode? uname -m to confirm.
